trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_OPTS: '-Dmaven.repo.local=$(Pipeline.Workspace)/.m2/repository'

steps:
- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: 'https://pkgs.dev.azure.com/igeadetokunbo0133/_packaging/maven_repo/maven/v1'

- script: chmod +x ./mvnw
  displayName: 'Set executable permission for mvnw'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    options: '-B -s settings.xml'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'deploy'
    options: '-B -s settings.xml'
